config/routes.rb
Myflix::Application.routes.draw do
  root to: 'pages#front'
  get 'home', to: 'videos#index'

  resources :videos, only: [:index, :show] do
    collection do
      post :search, to: 'videos#search'
    end
  end
  resources :categories, only: [:index, :show]
  get 'register', to: 'users#new'
  get 'sign_in', to: 'sessions#new'
  get 'sign_out', to: 'sessions#destroy'
  resources :users, only: [:create]
  resources :sessions, only: [:create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :videos, -> { order created_at: :desc  }
  validates_presence_of :name

  def recent_videos
    videos.first(6)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :password, :full_name
  validates_uniqueness_of :email

  has_secure_password validations: false
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category
  validates_presence_of :title, :description

  def self.search_by_title(search_term)
    return [] if search_term.blank?
    where("title LIKE ?", "%#{search_term}%").order("created_at DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_user
    redirect_to sign_in_path unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    redirect_to home_path if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if current_user
  end

  def create
    user = User.where(email: params[:email]).first
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: 'You are now signed in!'
    else
      flash[:error] = "Invalid email or password."
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path, notice: 'You are now signed out!'
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to home_path if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to sign_in_path 
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:full_name)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user
  
  def index
    @videos = Video.all
  end
  
  def show
    @video = Video.find(params[:id]) 
  end
  
  def search
    @results = Video.search_by_title(params[:search_term])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.haml
%article.video_category
  - @categories.each do |category|
    %header
      %h3= link_to category.name, category
    .videos.row
      - category.videos.each do |video|
        .video.col-sm-2
          %img(src="#{video.small_cover_url}")

app/views/categories/show.html.haml
%section.genre
  %header.clearfix
    %h1= @category.name
    .genre_sorting
      Sort by:
      %select(name="")
        %option(value="a-z") Title: A - Z
        %option(value="z-a") Title: Z - A
        %option(value="rating") Rating
  %article.row
    - @category.videos.each do |video|
      .video.col-md-2
        = link_to video do
          %img(src="#{video.small_cover_url}")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelflix</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title TRAVELSCReeN - a travel video on demand service
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
      = render 'shared/header'
    %section.content.clearfix
      = render 'shared/messages'
      = yield
    %footer
      &copy 2013 TRAVELSCReeN

app/views/pages/front.html.haml
%section.site_title
  %h1
    Unlimited Travel Movies for Only 9.99 a Month.
    = link_to "Sign Up Now!", register_path
  %p.sign_up
  %p.sign_in
    Have an account? Please
    = link_to "Sign In", sign_in_path

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "TRAVELSCReeN"
  - if current_user
    %ul.col-md-4.clearfix
      %li= link_to "Videos"
      %li= link_to "My Queue"
      %li= link_to "People"
    = form_tag search_videos_path, class: "span5 for-search" do
      %input.search-query(name="search_term" type="text" placeholder="Search for videos here")
      %button.btn.btn-default(type="submit") Search
    #user_links.pull-right
      %ul
        %li.dropdown
          %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
            Welcome, #{current_user.full_name}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              %a(href="#") Account
              %a(href="#") Plan and Billing
              = link_to 'Sign Out', sign_out_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/users/new.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @user, html: { class: "form-horizontal" } do |f|
        %header
          %h1 Register
        %fieldset
          = f.email_field :email, label: "Email Address"
          = f.password_field :password
          = f.text_field :full_name, label: "Full Name"
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            %input(type="submit" value="Sign Up" class="btn btn-default")

app/views/videos/index.html.haml
%article.video_category
  %header
    %h3= link_to "Comedy"
  .videos.row
    - @videos.each do |video|
      .video.col-sm-2
        = link_to video do
          %img(src="#{video.small_cover_url}")

app/views/videos/search.html.haml
%article.video_category
  - @results.each do |video|
    .video.span2
      = link_to video do
        %img(src="#{video.small_cover_url}")

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        %img(src="#{@video.large_cover_url}")
      .video_info.col-sm-3
        %header
          %h3= @video.title
          %span Rating: 4.5/5.0
        %p= @video.description
        .actions
          %a.btn.btn-primary(href="") Watch Now
          %a.btn.btn-default(href="") + My Queue